# Generated by Django 3.1.3 on 2020-11-06 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liveName', models.CharField(max_length=100, verbose_name='liveName')),
                ('liveUser', models.CharField(max_length=100, verbose_name='liveUser')),
                ('liveId', models.CharField(max_length=100, verbose_name='liveId')),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=100)),
                ('reactionCount', models.IntegerField(default=0)),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lives.live')),
            ],
        ),
    ]
